Stacked-Labs/poker-game

app/components/HomePage/HomeCard.tsx, app/components/HomePage/HomeNavBar.tsx, app/components/HomePage/Landing.tsx, app/components/HomePage/LandingSections/FAQsSection.tsx, app/components/HomePage/LandingSections/HomeSection.tsx, app/components/HomePage/LandingSections/RoadMapSection.tsx, app/components/HomePage/LandingSections/SocialsSection.tsx, app/components/HomePage/SocialsBox.tsx, app/components/HomePage/TitleText.tsx, app/components/TakeSeatModal.tsx, app/components/Web3Button.tsx, app/globals.css, app/interfaces.tsx, app/page.tsx, app/theme.ts, app/utils/FAQsData.ts
=> 31 home page layout and components

app/components/EmptySeatButton.tsx, app/components/Table.tsx, app/components/TakenSeatButton.tsx
=> refactor(TakenSeatButton): changed styling

.env, app/components/HomePage/HomeNavBar.tsx, app/components/Web3Button.tsx, app/contexts/AuthContext.tsx, app/contexts/WebSocketProvider.tsx, app/hooks/server_actions.ts, app/providers.tsx, next.config.js
Wip for the cookie implementation as well as websocket connection refresh.
=> wallet signing and jwt token recieving

app/components/TakeSeatModal.tsx
Resolves issue #60 
User is now required to have a connected wallet to join a table.
=> fix issue allowing user to take seat without connected wallet

app/components/EmptySeatButton.tsx, app/components/NavBar/Settings/PlayerList.tsx, app/components/Table.tsx, app/components/TakenSeatButton.tsx, app/game/[id]/layout.tsx, app/game/[id]/page.tsx, app/theme.ts
=> modify mobile views fixes #63

app/hooks/server_actions.ts
Changes made with the reconnection on backend for improved consistency.
- receiving and sending secure cookies for session management
- Handling refresh instances
=> working cookie passing for uuid and session consistency

app/components/Felt/Pot.tsx, app/components/Felt/index.tsx
=> make pot size responsive

app/components/NavBar/Chat/ChatBox.tsx, app/components/NavBar/Chat/SideBarChat.tsx, app/components/NavBar/index.tsx
=> fix chat ui

app/components/Card.tsx, app/components/Felt/CommunityCards.tsx, app/components/Table.tsx, app/components/TakenSeatButton.tsx
TODO:
- add animation
- recheck if folded in Card
- check TakenSeatButton for changes since Card was changed
=> Fix Community Cards UI

app/components/Web3Button.tsx, app/contexts/AuthContext.tsx, app/contexts/WebSocketProvider.tsx, app/hooks/server_actions.ts
- Introduced new `/logout` POST route for immediate auth and refresh token expiration
- Ensures complete session termination through server-side session clearing
- Implements MaxAge=-1 setting and session saving for thorough cleanup
- Dynamic cookie security configuration based on environment
- Production: Enforces HTTPS-only cookie transmission
- Development: Allows HTTP for testing purposes
- Enhanced session invalidation during logout process
- Migrated from local storage to secure HttpOnly cookies
- Implemented robust logout functionality
- Refined authentication state management using cookie presence
- Added comprehensive session termination capabilities
- Synchronized wallet disconnection with session logout
- Enhanced user authentication flow
- Improved security through …
=> change to secure cookie

app/game/[id]/page.tsx, app/hooks/server_actions.ts
demo: https://www.loom.com/share/15ba503c487a4be89fca624dcaf7cb1c?sid=86daa83e-f483-4f1b-ac0f-fbc6a19730ee
closes #90
=> Add handling for when user attempts to join a nonexistent table

app/components/CreateGame/PlayTypeToggle.tsx, app/components/HomePage/HomeNavBar.tsx, app/components/TakeSeatModal.tsx, go.mod
Initial Branch Changes resolved 95
91 is resolved however there will need to be back-end changes ass decimals are being introduced which is currently not supported. We can discuss.
94 is resolved by removing the unnecessary switch
=> 91 94 95 front end misc

.gitignore, app/components/CreateGame/GameSettingLeftSide.tsx, app/components/NavBar/Settings/AcceptedPlayers.tsx, app/components/NavBar/Settings/PendingPlayers.tsx, app/components/NavBar/Settings/PlayerList.tsx, app/components/NavBar/Settings/SettingsModal.tsx, app/components/NavBar/index.tsx, app/components/Table.tsx, app/components/TakeSeatModal.tsx, app/contexts/WebSocketProvider.tsx, app/game/[id]/page.tsx, app/hooks/server_actions.ts, app/hooks/usePendingPlayers.tsx, app/interfaces.tsx, app/theme.ts
- add api call
- add initial implementation for playerlist component
TODO:
- testing and debugging
- approve/deny/kick functionality
https://github.com/Stacked-Labs/poker-server/pull/20
=> Seat Request/Approve

app/components/NavBar/Settings/AcceptedPlayers.tsx, app/components/NavBar/Settings/PendingPlayers.tsx, app/components/NavBar/Settings/PlayerList.tsx, app/components/StartGameButton.tsx, app/hooks/server_actions.ts, app/hooks/useIsTableOwner.ts
- Added `isTableOwner` for `appState`
- `isTableOwner` is true in `handleCreateGame`
backend https://github.com/Stacked-Labs/poker-server/issues/27
closes #100
=> Start button visible to table owner only #100

app/components/Footer/RaiseInputBox.tsx, app/components/Footer/index.tsx, app/contexts/SoundProvider.tsx, app/contexts/WebSocketProvider.tsx, app/hooks/useAudio.ts, app/providers.tsx
Transferred audio triggers from action button on click handles to websocket messages
- added `if-else` statements in `new-log` WebSocket message
- action button handle methods calls `sendLog`, which returns a message that contains the words `calls`, `checks`, `folds`, and `raises`
closes #113
=> Transfer audio triggers to WebSocket messages

.cursor/rules/frontend-guidelines.mdc, .cursor/rules/repository-structure.mdc, app/components/NavBar/index.tsx, app/contexts/AppStoreProvider.tsx, app/contexts/WebSocketProvider.tsx, app/hooks/server_actions.ts, app/interfaces.tsx
Allow players to leave games when they want to.
- Also added cursor rules.
=> HandleLeave

app/components/HomePage/HomeCard.tsx, app/components/HomePage/HomeNavBar.tsx, app/components/HomePage/HomeSection.tsx, app/components/Web3Button.tsx, app/theme.ts
Made some adjustments to homepage elements
- transferred padding from parent to buttons so that "Stacked" text is really centered in the card (`HomeCard`)
- consistent padding for both buttons
closes #126
=> Fix homepage elements responsiveness

app/components/Felt/CommunityCards.tsx, app/components/Felt/Pot.tsx, app/components/Footer/index.tsx, app/components/StartGameButton.tsx, app/components/Table.tsx
Mostly deals with components' visibility when a game is running
- start button
- footer (action buttons)
- empty seat buttons
closes #119
=> error on deal

app/components/Footer/ActionButton.tsx, app/components/Footer/EmptyFooter.tsx, app/components/Footer/FooterWithActionButtons.tsx, app/components/Footer/RaiseInputBox.tsx, app/components/Footer/constants.ts, app/components/Footer/index.tsx
- `EmptyFooter.tsx`: footer component for non-betting state
- `FooterWithActionButtons.tsx`: encapsulates call/raise/check/fold buttons with hotkey support
- `constants.ts`: defines HOTKEY_BACK, HOTKEY_RAISE, HOTKEY_CALL, HOTKEY_CHECK, HOTKEY_FOLD
- `ActionButton.tsx`: added hotkey label
- `RaiseInputBox.tsx`: added isCurrentTurn prop, wired “b” and “r” hotkeys
- `Footer/index.tsx`: split empty footer and non-empty footer for readability and maintainability
Manual Testing: https://www.loom.com/share/27d001bb998740b5883e45bc258e009c?sid=55bcc20c-5432-46c9-9ff4-7b4d2685602a
closes #133
=> Add keyboard shortcuts

app/components/Table.tsx
Fixed seat numberings in `Table.tsx`
closes #139
=> Fix seat numberings

app/components/TakenSeatButton.tsx
noticed that there is no space between cards 
will create a ticket for this
closes #151
=> fix dealer button placement

app/components/Footer/FooterWithActionButtons.tsx, app/components/GuardModal.tsx
- Warning modal: “Check instead!”.
- Buttons: Back (close) and Fold Anyway (execute fold).
- Uses GuardModal when folding is possible but check is free.
- Fold button triggers modal or folds directly.
https://www.loom.com/share/d19db8821ccf4d34a6ac50eec62f7672?sid=ace653d7-8971-4e13-8ac0-05f6069186ca
Closes #182
=> Add guard modal for when a user folds #182
